#Update apt
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: "Install Common packages"
  apt: name={{ item }} state=present
  with_items:
   - net-tools
   - curl
  tags: installation_common

