- hosts: webstack
  become: yes
  roles:
    - common
  tags: common

- hosts: containers
  become: yes
  roles:
    - container
  tags: container_all

- hosts: loadbalancer
  become: yes
  roles:
    - loadbalancer
  tags: loadbalancer_all