- names: "Remove default configuration"
  file: path="/etc/nginx/sites-enabled/default" state=absent
  tags: configuration, remove_default_config

- name: "Deploy Nginx sites configuration"
  template: src=mysite.j2 dest="/etc/nginx/sites-enabled/mysite"
  notify: restart nginx
  tags: always, configuration, configuration_nginx